name: Publish Project Production In AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
            HOSTNAME: ${{ secrets.EC2_HOST }}
            USER_NAME: ec2-user


      - name: Debug Information
        run: |
           echo "Current Directory: $(pwd)"
           echo "Contents of Directory: $(ls)"
           echo "Value of Variable XYZ: $XYZ"      

      - name: Verify Secret Value
        run: | 
            echo "${{ secrets.AWS_SSH_KEY }}"

      - name: Configure SSH and Copy Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa 
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Start SSH Agent and Add Private Key
        run: |
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa

      - name: SSH into EC2 and Execute Commands
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo "Hello Git Actions"'