name: Publish Project Production In AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Information
        run: |
           echo "Current Directory: $(pwd)"
           echo "Contents of Directory: $(ls)"
           echo "Value of Variable XYZ: $XYZ"      

      #- name: Build Docker image
        #run: |
          #docker-compose -f docker-compose.prod.yml build

      - name: Execute SSH Commands into EC2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          port: 22
          script: |            
            echo "Hello GitActions"
            #IMAGEM="alexfariakof/infnet-devops-project"
            #container_id=$(docker ps -a -q --filter "ancestor=$IMAGEM")
            #image_id=$(docker images --format "{{.ID}}" "$IMAGEM")
            #echo $container_id
            #docker rm --force $container_id
            #docker run -d -p 42537:42537 $IMAGEM