name: Publish Project Production In AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build

      - name: Configure SSH and Copy Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker image to EC2
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no /home/ec2-user/docker-image.tar.gz ec2-user@ec2-34-239-129-207.compute-1.amazonaws.com:/home/ec2-user/

      - name: SSH into EC2 and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            docker load -i /home/ec2-user/docker-image.tar.gz
            rm -f /home/ec2-user/docker-image.tar.gz    
            pwd
            IMAGEM="alexfariakof/infnet-devops-project"
            container_id=$(docker ps -a -q --filter "ancestor=$IMAGEM")
            image_id=$(docker images --format "{{.ID}}" "$IMAGEM")
            echo $container_id
            docker rm --force $container_id
            docker run -d -p 42537:42537 $IMAGEM
